
version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: sudo tar -xvzf artifact.tar.gz -C ../ --strip 1
  AfterInstall:
      timeout: 180
  ApplicationStart:
      timeout: 3600
  ValidateService:
      timeout: 3600
     