version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn test -Dtest=AppTest
      - mvn package
      - cp appspec.yml target/
      - tar -cvzf artifact.tar.gz target/
artifacts:
  files:
    - artifact.tar.gz