version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn test -Dtest=AppTest
      - mvn package
      - tar -cvzf artifact.tar.gz build-deploy-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - artifact.tar.gz