
version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: tar -xvzf artifact.tar.gz --strip 1
  AfterInstall:
      timeout: 180
  ApplicationStart:
      timeout: 3600
  ValidateService:
      timeout: 3600
     